 # Simple workflow for deploying static content to GitHub Pages
    2 name: Deploy static content to Pages
    3 on:
    4   # Runs on pushes targeting the default branch
    5   push:
    6     branches: ["main"]
    7
    8   # Allows you to run this workflow manually from the Actions tab
    9   workflow_dispatch:
   10
   11 # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
   12 permissions:
   13   contents: read
   14   pages: write
   15   id-token: write
   16
   17 # Allow only one concurrent deployment, skipping runs queued between the run in-progress and
      latest queued.
   18 # However, do NOT cancel in-progress runs as we want to allow these production deployments to
      complete.
   19 concurrency:
   20   group: "pages"
   21   cancel-in-progress: false
   22
   23 jobs:
   24   # Single deploy job since we're just deploying
   25   deploy:
   26     environment:
   27       name: github-pages
   28       url: ${{ steps.deployment.outputs.page_url }}
   29     runs-on: ubuntu-latest
   30     steps:
   31       - name: Checkout
   32         uses: actions/checkout@v4
   33       - name: Set up Node.js
   34         uses: actions/setup-node@v2
   35         with:
   36           node-version: '18' # Or your preferred Node.js version
   37
   38       - name: Install dependencies
   39         run: npm install
   40
   41       - name: Build project
   42         run: npm run build
   43
   44       - name: Setup Pages
   45         uses: actions/configure-pages@v5
   46       - name: Upload artifact
   47         uses: actions/upload-pages-artifact@v3
   48         with:
   49           # Upload the build output directory
   50           path: './dist'
   51       - name: Deploy to GitHub Pages
   52         id: deployment
   53         uses: actions/deploy-pages@v4
